### ISSUE TITLE
PHP 5.4+

### ISSUE THREAD

**Issue by thiagodp** [malukenho/speaknumber#16]
Olá Jeferrson,
poderia rodar os testes com o travis-ci para PHP 5.4? Essa versão já suportava traits. Se o projeto não estiver usando coisas de versões posteriores do PHP, é possível que rode nesta também (e nesse caso, podereria-se diminuir a dependência de versão no composer).

**Comment by malukenho** [comment]
@thiagodp sim, poderiamos habilitar o travis para a versão 5.4 do php. No entanto, esta versão já teve seu ciclo finalizado. Sendo assim, não acho muito interessante dar suporte para versões antigas do PHP.

http://php.net/supported-versions.php

/cc @CentaurWarchief

**Comment by CentaurWarchief** [comment]
Penso o mesmo que o @malukenho em relação ao suporte do PHP 5.4 ter acabado.

**Comment by thiagodp** [comment]
Penso que a questão seja o número de servidores de hospedagem que ainda estão rodando versões mais antigas. O GoDaddy, por exemplo, que é um dos grandes serviços mundiais de hospedagem, roda PHP 5.4. Assim, talvez diminuindo o requisito de dependência, aumente a compatibilidade da biblioteca e o número de usuários. Só uma sugestão...

**Comment by CentaurWarchief** [comment]
@thiagodp Você pode instalar a biblioteca ignorando a regra para a versão do PHP: `composer install --ignore-platform-reqs=php malukenho/speaknumber`.

O ponto é que: você cedendo para PHP54, acaba deixando brecha pra pedirem compatibilidade pra 53... e daí pra pior, porque se for levar em conta, há muitos servidores rodando essas versões. O problema de manter compatibilidade com versões antigas é que ela impede a evolução, e se for depender dos `usuários` para atualizarem, nunca acontecerá.

**Comment by thiagodp** [comment]
@CentaurWarchief Creio que não. Uma biblioteca pode ter a versão 1.0 compatível com PHP 5.3, a 2.0 com PHP 5.4 e assim por diante, caso necessário. Basta que seja feito um controle de versão adequado. Assim não há impedimento da evolução. Não só isso, cada usuário que estiver interessado na compatibilidade com uma versão do PHP específica, poderia usar a versão da biblioteca correspondente. Se vocês amanhã vierem a fazer uma versão compatível com PHP 7, por exemplo, os usuários não serão forçados a fazer o upgrade. Assim como não serão forçados a fazer o downgrade para versões anteriores depois.

**Comment by CentaurWarchief** [comment]
Verdade. E como você sugere que mantemos isso? Acho que dá pra fazer o seguinte, na 1.0 deixamos `~5.4|~5.5` e seguimos 2.x com PHP7 (já fazendo type-hint de retorno e etc).

O que acha? @malukenho

**Comment by malukenho** [comment]
@thiagodp a questão é bem mais profunda. Liberando versões antigas do PHP, estaremos influenciando a comunidade a não fazer upgrade de suas versões antigas caso queira usar a biblioteca. Desta forma, o numero de servidores com versões ultrapassadas e desatualizadas vai continuar a crescer muito.

Parece-me que, atualizar o php não é uma questão tão preocupante para empresas e programadores, não como deveria ser (Pelo menos não se comparado ao java).

Se você usa um servidor com versão desatualizada, você deve atualiza-ló até mesmo por questões de segurança. Qualquer servidor que me ofereça 5.4 como única alternativa, olharei auspiciosamente.

> Uma biblioteca pode ter a versão 1.0 compatível com PHP 5.3, a 2.0 com PHP 5.4 e assim por diante, caso necessário. Basta que seja feito um controle de versão adequado. 

Exatamente.

@CentaurWarchief no commit #18  nos temos `~5.5|~7.0`, porém acho a divisão de versões válida.

Não temos uma tag ainda no repô, vou trabalhar em algumas pequenas coisa hoje durante o dia.

Provavelmente, amanhã poderemos criar a primeira versão `1.0.0`.

**Comment by thiagodp** [comment]
Legal. Acredito que seja interessante manter a dependência do PHP sempre na versão mais baixa dele em que o código consegue rodar. Assim, mais usuários podem se beneficiar com a biblioteca.

Sendo necessário/desejado usar um recurso novo, sobe-se a versão da biblioteca junto com o requisito do PHP.

@malukenho Concordo que não é o ideal rodarmos versões antigas, também pelo lado da segurança. O problema é que, infelizmente, nem sempre um cliente está disposto a trocar de serviço de hospedagem ou realizar a atualização...

Abs!

**Comment by malukenho** [comment]
@thiagodp de qualquer forma, encorajamos que se realmente necessário usar tal recurso. Deve-se usar as extensões `Intl` escritas em `C` sempre que possível.

Abraços e obrigado pelo feedback.

**Comment by thiagodp** [comment]
Ah, a propósito, pode ser uma boa adotar [versiomento semântico](http://semver.org/lang/pt-BR/). Fica a sugestão...

**Comment by malukenho** [comment]
@thiagodp thanks. Iremos adotar o **semantic version** :+1:
