### ISSUE TITLE
Semantic Versioning 2.0.0

### ISSUE THREAD

**Issue by italolelis** [malukenho/speaknumber#8]
Que tal gerar uma tag estável da biblioteca? Isso permite que o composer não carregue o dev-master e possamos trabalhar com o Semantic Versioning 2.0.0. 

Dá uma olhada e vê se é legal: http://semver.org/

**Comment by Fuhrmann** [comment]
Yes, please!

**Comment by malukenho** [comment]
@CentaurWarchief @Fuhrmann @italolelis tag `1.0.0` has been created :beers: :

**Comment by Fuhrmann** [comment]
:+1: Thanks!

**Comment by CentaurWarchief** [comment]
:beers:

**Comment by italolelis** [comment]
Thanks :+1:
